layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

BASE_PATH: nihaarshah.github.io/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects: Nihaar1996.github.io
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
#   linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
#   twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Resume
    web_url: https://nihaarshah.github.io/resume

  - name: Normalizing flows for Anomaly Detection
    web_url: https://nihaarshah.github.io/Nflow_AD

  - name: Hierarchical Neural Time Series Decoding
    web_url: https://nihaarshah.github.io/hierarchical_neuro

  - name: Curiosity-driven exploration in Deep Reinforcement Learning for Robotics
    web_url: https://nihaarshah.github.io/DeepRL_curiosity

  - name: Survey on the theory of Causal Online Learning
    web_url: https://nihaarshah.github.io/project_pdfs/ML_Theory_Project_Report.pdf

  - name: Calibrate a Camera for Visual Odometry
    web_url: https://nihaarshah.github.io/CalibrateCamera

  - name: Deep learning with Radars for autonomous vehicles
    web_url: https://nihaarshah.github.io/deep_radar

  - name: Probabilistic Programming for Bayesian Demand Estimation of Bike Sharing
    web_url: https://nihaarshah.github.io/prob_prog_demand

  - name: Causal Minimal Interventions
    web_url: https://nihaarshah.github.io/causal_interventions

theme: jekyll-theme-cayman
